//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIDemoDec19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public int Id { get; set; }
        public Nullable<int> cId { get; set; }
        public Nullable<int> mark { get; set; }
        public Nullable<int> uId { get; set; }
        public Nullable<int> gId { get; set; }
        public Nullable<int> assId { get; set; }
        public Nullable<System.DateTime> assDate { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
