//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIDemoDec19
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectAssessment
    {
        public int Id { get; set; }
        public Nullable<int> asId { get; set; }
        public Nullable<int> sId { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
