//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIDemoDec19
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordCloud
    {
        public int Id { get; set; }
        public string Words { get; set; }
        public string Description { get; set; }
        public Nullable<int> fbId { get; set; }
    
        public virtual Feedback Feedback { get; set; }
    }
}
